export const FIELD_TYPES = {
  en: {
    RECORD_NUMBER: 'Record number',
    __ID__: 'Record ID',
    __REVISION__: 'Revision',
    CREATOR: 'Created by',
    CREATED_TIME: 'Created datetime',
    MODIFIER: 'Updated by',
    UPDATED_TIME: 'Updated datetime',
    SINGLE_LINE_TEXT: 'Text',
    MULTI_LINE_TEXT: 'Text area',
    RICH_TEXT: 'Rich text',
    NUMBER: 'Number',
    CALC: 'Calculated',
    CHECK_BOX: 'Check box',
    RADIO_BUTTON: 'Radio button',
    MULTI_SELECT: 'Multi-choice',
    DROP_DOWN: 'Drop-down',
    USER_SELECT: 'User selection',
    ORGANIZATION_SELECT: 'Department Selection',
    GROUP_SELECT: 'Group Selection',
    DATE: 'Date',
    TIME: 'Time',
    DATETIME: 'Date and time',
    LINK: 'Link',
    FILE: 'Attachment',
    SUBTABLE: 'Table',
    REFERENCE_TABLE: 'Related records',
    CATEGORY: 'Categories',
    STATUS: 'Status',
    STATUS_ASSIGNEE: 'Assignee',
    LABEL: 'Label',
    SPACER: 'Space',
    HR: 'Border',
    GROUP: 'Field group'
  },
  ja: {
    RECORD_NUMBER: 'レコード番号',
    __ID__: 'レコードID',
    __REVISION__: 'リビジョン',
    CREATOR: '作成者',
    CREATED_TIME: '作成日時',
    MODIFIER: '更新者',
    UPDATED_TIME: '更新日時',
    SINGLE_LINE_TEXT: '文字列（1行）',
    MULTI_LINE_TEXT: '文字列（複数行）',
    RICH_TEXT: 'リッチエディター',
    NUMBER: '数値',
    CALC: '計算',
    CHECK_BOX: 'チェックボックス',
    RADIO_BUTTON: 'ラジオボタン',
    MULTI_SELECT: '複数選択',
    DROP_DOWN: 'ドロップダウン',
    USER_SELECT: 'ユーザー選択',
    ORGANIZATION_SELECT: '組織選択',
    GROUP_SELECT: 'グループ選択',
    DATE: '日付',
    TIME: '時刻',
    DATETIME: '日時',
    LINK: 'リンク',
    FILE: '添付ファイル',
    SUBTABLE: 'テーブル',
    REFERENCE_TABLE: '関連レコード一覧',
    CATEGORY: 'カテゴリー',
    STATUS: 'ステータス',
    STATUS_ASSIGNEE: '作業者',
    LABEL: 'ラベル',
    SPACER: 'スペース',
    HR: '罫線',
    GROUP: 'グループ'
  }
};

export const BUILTIN_FIELD_TYPES = [
  '__ID__',
  'RECORD_NUMBER',
  '__REVISION__',
  'CREATOR',
  'CREATED_TIME',
  'MODIFIER',
  'UPDATED_TIME',
  'STATUS',
  'STATUS_ASSIGNEE',
  'CATEGORY'
];
